module.exports = {

  aboutUs: "AFTER YEARS OF DREAMING, SAVING, AND PLANNING, WE FOUND THE PERFECT PLACE IN THE HEART OF OUR COMMUNITY WHERE WE COULD SHARE OUR LOVE OF CRAFT BEER AND GREAT FOOD. SAVING A STRIP OF LAND IN CANAL PARK FROM BEING TURNED INTO ANOTHER PARKING LOT, WE INVESTED CONSIDERABLE TIME AND MONEY INTO CLEANING UP YEARS OF SOIL CONTAMINATION LEFT OVER FROM A LONG HISTORY OF INDUSTRIAL POLLUTION. TODAY THE BREWERY SITS ON PRISTINE LAND WITH AMAZING VIEWS OF LAKE SUPERIOR AND DOWNTOWN DULUTH. CONTINUAL EFFORTS ARE MADE TO SUPPORT OTHER LOCAL BUSINESSES, THE COMMUNITY, AND THE ENVIRONMENT, AS WELL AS PROVIDE HIGH-QUALITY FOOD AND DRINK WITH SUSTAINABLY SOURCED INGREDIENTS, OFTEN ORGANIC AND LOCAL."
  
}
